// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.3
// - protoc             v5.29.3
// source: api/shorturl/v1/shorturl.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShorturlCreateShorturl = "/api.shorturl.v1.Shorturl/CreateShorturl"
const OperationShorturlHello = "/api.shorturl.v1.Shorturl/Hello"

type ShorturlHTTPServer interface {
	CreateShorturl(context.Context, *CreateShorturlRequest) (*CreateShorturlReply, error)
	Hello(context.Context, *HelloReq) (*HelloResp, error)
}

func RegisterShorturlHTTPServer(s *http.Server, srv ShorturlHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/shorturl", _Shorturl_CreateShorturl0_HTTP_Handler(srv))
	r.GET("/helloshort/{name}", _Shorturl_Hello0_HTTP_Handler(srv))
}

func _Shorturl_CreateShorturl0_HTTP_Handler(srv ShorturlHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateShorturlRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShorturlCreateShorturl)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateShorturl(ctx, req.(*CreateShorturlRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateShorturlReply)
		return ctx.Result(200, reply)
	}
}

func _Shorturl_Hello0_HTTP_Handler(srv ShorturlHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShorturlHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Hello(ctx, req.(*HelloReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloResp)
		return ctx.Result(200, reply)
	}
}

type ShorturlHTTPClient interface {
	CreateShorturl(ctx context.Context, req *CreateShorturlRequest, opts ...http.CallOption) (rsp *CreateShorturlReply, err error)
	Hello(ctx context.Context, req *HelloReq, opts ...http.CallOption) (rsp *HelloResp, err error)
}

type ShorturlHTTPClientImpl struct {
	cc *http.Client
}

func NewShorturlHTTPClient(client *http.Client) ShorturlHTTPClient {
	return &ShorturlHTTPClientImpl{client}
}

func (c *ShorturlHTTPClientImpl) CreateShorturl(ctx context.Context, in *CreateShorturlRequest, opts ...http.CallOption) (*CreateShorturlReply, error) {
	var out CreateShorturlReply
	pattern := "/v1/shorturl"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShorturlCreateShorturl))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShorturlHTTPClientImpl) Hello(ctx context.Context, in *HelloReq, opts ...http.CallOption) (*HelloResp, error) {
	var out HelloResp
	pattern := "/helloshort/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShorturlHello))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
